import Image from "../../src/assets/aboutusimage.png";
export const cards = [
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 100,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "1 bed",
    title: "Apartment in maadi",
    type: "Elevens Deluxe King Studio",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 150,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "2 beds",
    title: "Apartment in maadi",
    type: "Elevens one bedroom",
  },
  {
    cost: 200,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "3 beds",
    title: "Apartment in maadi",
    type: "Elevens  triplex",
  },
  {
    cost: 200,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "3 beds",
    title: "Apartment in maadi",
    type: "Elevens  triplex",
  },
  {
    cost: 200,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "4 beds",
    title: "Apartment in maadi",
    type: "Elevens  pentahouse",
  },
  {
    cost: 200,
    images: [Image, Image, Image, Image],
    link: "/aboutus",
    room: "4 beds",
    title: "Apartment in maadi",
    type: "Elevens  pentahouse",
  },
];
